project_id = "kjibbbuceipnialfgflt"

[functions.create-tenant]
verify_jwt = false

[functions.yoco-checkout]
verify_jwt = false

[functions.yoco-webhook]
verify_jwt = false

[functions.send-booking-email]
verify_jwt = false

[functions.places-autocomplete]
verify_jwt = false
