import SiteHeader from "@/components/site/SiteHeader";
import SiteFooter from "@/components/site/SiteFooter";

const Privacy = () => (
  <div className="min-h-screen nextslot-theme bg-background animate-fade-in">
    <SiteHeader />
    <main className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
      <div className="mb-12 space-y-4">
        <h1 className="text-4xl md:text-5xl font-bold leading-tight animate-slide-down">Privacy Policy</h1>
        <p className="text-muted-foreground animate-slide-up stagger-1">Last updated: 8 March 2026</p>
      </div>
      <div className="prose prose-lg max-w-none space-y-8">
        <section><h2 className="text-2xl font-bold mb-4">Introduction</h2><p className="text-muted-foreground">NextSlot ("we", "us", or "our") is committed to protecting your personal information in accordance with the Protection of Personal Information Act 4 of 2013 ("POPIA") and all other applicable South African legislation. This Privacy Policy explains how we collect, use, store, and protect your personal information when you use our website and services.</p></section>
        <section><h2 className="text-2xl font-bold mb-4">Responsible Party</h2><p className="text-muted-foreground">In terms of POPIA, NextSlot is the responsible party for the processing of your personal information. Our Information Officer can be contacted at:</p><p className="text-muted-foreground mt-4">Email: privacy@nextslot.co.za<br />Address: South Africa</p></section>
        <section><h2 className="text-2xl font-bold mb-4">Personal Information We Collect</h2><p className="text-muted-foreground mb-4">We collect personal information as defined in POPIA, which may include:</p><ul className="list-disc pl-6 space-y-2 text-muted-foreground"><li>Full name and surname</li><li>Email address and contact number</li><li>Physical or postal address</li><li>Booking history and service preferences</li><li>Payment information (processed securely via third-party providers)</li><li>Device and browser information collected automatically</li><li>IP address and location data</li></ul></section>
        <section><h2 className="text-2xl font-bold mb-4">Purpose and Lawful Basis for Processing</h2><p className="text-muted-foreground mb-4">In accordance with Section 9 of POPIA, we process your personal information for the following lawful purposes:</p><ul className="list-disc pl-6 space-y-2 text-muted-foreground"><li>To provide and manage our booking services (contractual necessity)</li><li>To communicate with you about your bookings and account (legitimate interest)</li><li>To send marketing communications where you have given consent</li><li>To comply with legal obligations under South African law</li><li>To improve and personalise our services (legitimate interest)</li><li>To prevent fraud and ensure the security of our platform</li></ul></section>
        <section><h2 className="text-2xl font-bold mb-4">Consent</h2><p className="text-muted-foreground">Where we rely on your consent to process personal information, you have the right to withdraw that consent at any time. Withdrawal of consent does not affect the lawfulness of processing carried out before the withdrawal. You may withdraw consent by contacting us at privacy@nextslot.co.za.</p></section>
        <section><h2 className="text-2xl font-bold mb-4">Retention of Personal Information</h2><p className="text-muted-foreground">In terms of Section 14 of POPIA, we retain your personal information only for as long as is necessary to fulfil the purposes for which it was collected, or as required by applicable law (including tax and accounting requirements). When personal information is no longer needed, it will be securely destroyed or de-identified.</p></section>
        <section><h2 className="text-2xl font-bold mb-4">Sharing of Personal Information</h2><p className="text-muted-foreground mb-4">We may share your personal information with:</p><ul className="list-disc pl-6 space-y-2 text-muted-foreground"><li>Service providers who book through our platform (limited to what is necessary to fulfil the booking)</li><li>Third-party payment processors for secure payment handling</li><li>Service providers who assist us in operating our platform (e.g., hosting, analytics)</li><li>Regulatory authorities where required by law</li></ul><p className="text-muted-foreground mt-4">We do not sell your personal information to third parties. Where personal information is transferred outside of South Africa, we ensure adequate safeguards are in place as required by Section 72 of POPIA.</p></section>
        <section><h2 className="text-2xl font-bold mb-4">Security Safeguards</h2><p className="text-muted-foreground">In accordance with Section 19 of POPIA, we implement appropriate technical and organisational measures to protect your personal information against unauthorised access, loss, destruction, or damage. These measures include encryption, access controls, and regular security assessments. In the event of a data breach, we will notify you and the Information Regulator as required by Section 22 of POPIA.</p></section>
        <section><h2 className="text-2xl font-bold mb-4">Your Rights Under POPIA</h2><p className="text-muted-foreground mb-4">As a data subject, you have the following rights under POPIA:</p><ul className="list-disc pl-6 space-y-2 text-muted-foreground"><li>The right to be notified that your personal information is being collected (Section 18)</li><li>The right to access your personal information (Section 23)</li><li>The right to request correction or deletion of your personal information (Section 24)</li><li>The right to object to the processing of your personal information (Section 11(3))</li><li>The right not to be subject to automated decision-making (Section 71)</li><li>The right to lodge a complaint with the Information Regulator</li></ul><p className="text-muted-foreground mt-4">To exercise any of these rights, please contact our Information Officer at privacy@nextslot.co.za.</p></section>
        <section><h2 className="text-2xl font-bold mb-4">Cookies and Tracking Technologies</h2><p className="text-muted-foreground">We use cookies and similar technologies to enhance your experience. You can manage your cookie preferences through your browser settings. Refusing cookies may affect the functionality of our website.</p></section>
        <section><h2 className="text-2xl font-bold mb-4">Children's Privacy</h2><p className="text-muted-foreground">Our services are not directed at children under the age of 18. We do not knowingly collect personal information from children without the consent of a competent person as required by Section 35 of POPIA.</p></section>
        <section><h2 className="text-2xl font-bold mb-4">Changes to This Policy</h2><p className="text-muted-foreground">We may update this Privacy Policy from time to time. We will notify you of material changes by posting the updated policy on our website and updating the "Last updated" date.</p></section>
        <section><h2 className="text-2xl font-bold mb-4">Complaints</h2><p className="text-muted-foreground">If you are not satisfied with how we handle your personal information, you have the right to lodge a complaint with the Information Regulator:</p><p className="text-muted-foreground mt-4">The Information Regulator (South Africa)<br />Email: enquiries@inforegulator.org.za<br />Website: www.justice.gov.za/inforeg</p></section>
        <section><h2 className="text-2xl font-bold mb-4">Contact Us</h2><p className="text-muted-foreground">If you have any questions about this Privacy Policy or wish to exercise your rights, please contact us at:</p><p className="text-muted-foreground mt-4">Email: privacy@nextslot.co.za<br />Address: South Africa</p></section>
      </div>
    </main>
    <SiteFooter />
  </div>
);

export default Privacy;
