import SiteHeader from "@/components/site/SiteHeader";
import SiteFooter from "@/components/site/SiteFooter";

const Privacy = () => (
  <div className="min-h-screen nextslot-theme bg-background animate-fade-in">
    <SiteHeader />
    <main className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
      <div className="mb-12 space-y-4">
        <h1 className="text-4xl md:text-5xl font-bold leading-tight animate-slide-down">Privacy Policy</h1>
        <p className="text-muted-foreground animate-slide-up stagger-1">Last updated: 8 March 2026</p>
      </div>
      <div className="prose prose-lg max-w-none space-y-8">
        <section><h2 className="text-2xl font-bold mb-4">Introduction</h2><p className="text-muted-foreground">NextSlot ("we", "us", or "our") is committed to protecting your personal information in accordance with the Protection of Personal Information Act 4 of 2013 ("POPIA") and all other applicable South African legislation. This Privacy Policy explains how we collect, use, store, and protect your personal information when you use our website and services.</p></section>
        <section><h2 className="text-2xl font-bold mb-4">Responsible Party</h2><p className="text-muted-foreground">In terms of POPIA, NextSlot is the responsible party for the processing of your personal information. Our Information Officer can be contacted at:</p><p className="text-muted-foreground mt-4">Email: privacy@nextslot.co.za<br />Address: South Africa</p></section>
        <section><h2 className="text-2xl font-bold mb-4">Personal Information We Collect</h2><p className="text-muted-foreground mb-4">We collect personal information as defined in POPIA, which may include:</p><ul className="list-disc pl-6 space-y-2 text-muted-foreground"><li>Full name and surname</li><li>Email address and contact number</li><li>Physical or postal address</li><li>Booking history and service preferences</li><li>Payment information (processed securely via third-party providers)</li><li>Device and browser information collected automatically</li><li>IP address and location data</li></ul></section>
        <section><h2 className="text-2xl font-bold mb-4">Purpose and Lawful Basis for Processing</h2><p className="text-muted-foreground mb-4">In accordance with Section 9 of POPIA, we process your personal information for the following lawful purposes:</p><ul className="list-disc pl-6 space-y-2 text-muted-foreground"><li>To provide and manage our booking services (contractual necessity)</li><li>To communicate with you about your bookings and account (legitimate interest)</li><li>To send marketing communications where you have given consent</li><li>To comply with legal obligations under South African law</li><li>To improve and personalise our services (legitimate interest)</li><li>To prevent fraud and ensure the security of our platform</li></ul></section>
        <section><h2 className="text-2xl font-bold mb-4">Consent</h2><p className="text-muted-foreground">Where we rely on your consent to process personal information, you have the right to withdraw that consent at any time. Withdrawal of consent does not affect the lawfulness of processing carried out before the withdrawal.</p></section>
        <section><h2 className="text-2xl font-bold mb-4">Sharing of Personal Information</h2><p className="text-muted-foreground mb-4">We may share your personal information with:</p><ul className="list-disc pl-6 space-y-2 text-muted-foreground"><li>Service Providers who need it to fulfil your bookings</li><li>Payment processors and financial institutions</li><li>Technology and hosting service providers</li><li>Law enforcement or regulatory authorities where required by South African law</li></ul><p className="text-muted-foreground mt-4">We do not sell your personal information to third parties.</p></section>
        <section><h2 className="text-2xl font-bold mb-4">Transborder Flows</h2><p className="text-muted-foreground">Where personal information is transferred outside South Africa, we ensure that the recipient country or organisation provides an adequate level of protection as required by Section 72 of POPIA, or that appropriate safeguards are in place.</p></section>
        <section><h2 className="text-2xl font-bold mb-4">Retention of Personal Information</h2><p className="text-muted-foreground">We retain your personal information for as long as necessary to fulfil the purposes for which it was collected, or as required by South African law. When information is no longer required, it is securely deleted or anonymised in accordance with POPIA.</p></section>
        <section><h2 className="text-2xl font-bold mb-4">Security Measures</h2><p className="text-muted-foreground">We implement appropriate technical and organisational security measures to protect your personal information against unauthorised access, loss, or destruction, as required by Section 19 of POPIA. However, no method of transmission over the internet is completely secure.</p></section>
        <section><h2 className="text-2xl font-bold mb-4">Your Rights Under POPIA</h2><p className="text-muted-foreground mb-4">As a data subject under POPIA, you have the right to:</p><ul className="list-disc pl-6 space-y-2 text-muted-foreground"><li>Request access to your personal information (Section 23)</li><li>Request correction or deletion of your personal information (Section 24)</li><li>Object to the processing of your personal information (Section 11(3))</li><li>Submit a complaint to the Information Regulator</li><li>Institute civil proceedings for damages</li></ul></section>
        <section><h2 className="text-2xl font-bold mb-4">Cookies and Tracking</h2><p className="text-muted-foreground">We use cookies and similar tracking technologies to improve your experience on our platform. You can control cookie settings through your browser. Essential cookies required for the platform to function cannot be disabled. By continuing to use our platform, you consent to our use of cookies as described in this policy.</p></section>
        <section><h2 className="text-2xl font-bold mb-4">Direct Marketing</h2><p className="text-muted-foreground">In terms of Section 69 of POPIA, we will only send you direct marketing communications where you have given your consent or where we have an existing relationship with you and you have not opted out. You may opt out of marketing communications at any time by clicking the unsubscribe link in our emails or contacting us directly.</p></section>
        <section><h2 className="text-2xl font-bold mb-4">Information Regulator</h2><p className="text-muted-foreground">If you believe we have not complied with POPIA, you have the right to lodge a complaint with the Information Regulator of South Africa:</p><p className="text-muted-foreground mt-4">Website: www.inforegulator.org.za<br />Email: inforeg@justice.gov.za</p></section>
        <section><h2 className="text-2xl font-bold mb-4">Changes to This Policy</h2><p className="text-muted-foreground">We may update this Privacy Policy from time to time to reflect changes in our practices or South African legislation. Material changes will be communicated via email or a prominent notice on our platform. We encourage you to review this policy periodically.</p></section>
        <section><h2 className="text-2xl font-bold mb-4">Contact Us</h2><p className="text-muted-foreground">For any privacy-related queries or to exercise your rights under POPIA, please contact our Information Officer:</p><p className="text-muted-foreground mt-4">Email: privacy@nextslot.co.za<br />Address: South Africa</p></section>
      </div>
    </main>
    <SiteFooter />
  </div>
);

export default Privacy;
