import SiteHeader from "@/components/site/SiteHeader";

const SiteTerms = () => (
  <div className="min-h-screen nextslot-theme bg-background animate-fade-in">
    <SiteHeader />
    <main className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
      <div className="mb-12 space-y-4">
        <h1 className="text-4xl md:text-5xl font-bold leading-tight animate-slide-down">Terms of Service</h1>
        <p className="text-muted-foreground animate-slide-up stagger-1">Last updated: 8 March 2026</p>
      </div>
      <div className="prose prose-lg max-w-none space-y-8">
        <section><h2 className="text-2xl font-bold mb-4">Agreement to Terms</h2><p className="text-muted-foreground">By accessing or using NextSlot's website and services, you agree to be bound by these Terms of Service and all applicable South African laws and regulations, including the Consumer Protection Act 68 of 2008 ("CPA"), the Electronic Communications and Transactions Act 25 of 2002 ("ECTA"), and the Protection of Personal Information Act 4 of 2013 ("POPIA"). If you do not agree, you must discontinue use immediately.</p></section>
        <section><h2 className="text-2xl font-bold mb-4">Definitions</h2><ul className="list-disc pl-6 space-y-2 text-muted-foreground"><li><strong>"NextSlot"</strong>, <strong>"we"</strong>, <strong>"us"</strong> or <strong>"our"</strong> refers to NextSlot, a South African service.</li><li><strong>"User"</strong>, <strong>"you"</strong> or <strong>"your"</strong> refers to any person accessing or using our services.</li><li><strong>"Service Provider"</strong> refers to barbers, beauticians, photographers, tattoo artists, and other professionals using NextSlot.</li><li><strong>"Platform"</strong> refers to our website, mobile applications, and related services.</li></ul></section>
        <section><h2 className="text-2xl font-bold mb-4">Eligibility</h2><p className="text-muted-foreground">You must be at least 18 years of age to use our services. By using NextSlot, you represent and warrant that you have the legal capacity to enter into a binding agreement under South African law.</p></section>
        <section><h2 className="text-2xl font-bold mb-4">Description of Services</h2><p className="text-muted-foreground">NextSlot provides an online booking and management platform for independent service providers. We act as an intermediary and do not provide the underlying services (e.g., haircuts, beauty treatments, photography). The contract for services is between you and the relevant Service Provider.</p></section>
        <section><h2 className="text-2xl font-bold mb-4">User Obligations</h2><p className="text-muted-foreground mb-4">You agree to:</p><ul className="list-disc pl-6 space-y-2 text-muted-foreground"><li>Provide accurate and complete information when registering or making bookings</li><li>Keep your account credentials secure and confidential</li><li>Not use the platform for any unlawful purpose or in violation of any South African law</li><li>Not attempt to gain unauthorised access to any part of the platform</li><li>Not transmit harmful code, spam, or unsolicited communications</li><li>Not impersonate another person or entity</li></ul></section>
        <section><h2 className="text-2xl font-bold mb-4">Bookings and Cancellations</h2><p className="text-muted-foreground">Bookings made through NextSlot are subject to the availability and terms set by individual Service Providers. Cancellation policies are determined by each Service Provider and will be displayed at the time of booking. In terms of the CPA, you may have cooling-off rights in certain circumstances.</p></section>
        <section><h2 className="text-2xl font-bold mb-4">Fees and Payment</h2><p className="text-muted-foreground">All fees are displayed in South African Rand (ZAR) and include VAT where applicable, in accordance with the Value-Added Tax Act 89 of 1991. Payment terms and methods will be clearly communicated before any transaction. We reserve the right to amend our fees with reasonable notice.</p></section>
        <section><h2 className="text-2xl font-bold mb-4">Intellectual Property</h2><p className="text-muted-foreground">All content on NextSlot, including text, graphics, logos, software, and designs, is the property of NextSlot or its licensors and is protected under the Copyright Act 98 of 1978 and the Trade Marks Act 194 of 1993. You may not reproduce, distribute, or create derivative works without our prior written consent.</p></section>
        <section><h2 className="text-2xl font-bold mb-4">User Content</h2><p className="text-muted-foreground">Where you submit content (such as reviews or comments), you grant NextSlot a non-exclusive, royalty-free licence to use, display, and distribute such content on our platform. You warrant that you have the right to share any content you submit and that it does not infringe any third-party rights or contravene South African law.</p></section>
        <section><h2 className="text-2xl font-bold mb-4">Privacy and Personal Information</h2><p className="text-muted-foreground">Your personal information is processed in accordance with our Privacy Policy and the Protection of Personal Information Act 4 of 2013. By using our services, you acknowledge that you have read and understood our Privacy Policy.</p></section>
        <section><h2 className="text-2xl font-bold mb-4">Electronic Communications</h2><p className="text-muted-foreground">In terms of ECTA, this agreement constitutes a valid and enforceable electronic agreement. Any electronic communications, including emails and notifications sent through the platform, are deemed to have been received by you when they enter your information system.</p></section>
        <section><h2 className="text-2xl font-bold mb-4">Limitation of Liability</h2><p className="text-muted-foreground">To the fullest extent permitted by South African law, NextSlot shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of the platform. Our total liability shall not exceed the amount paid by you to NextSlot in the 12 months preceding the claim. Nothing in these terms excludes liability that cannot be excluded under the CPA or other mandatory legislation.</p></section>
        <section><h2 className="text-2xl font-bold mb-4">Disclaimer of Warranties</h2><p className="text-muted-foreground">Our platform is provided "as is" and "as available". While we strive to ensure reliability, we do not warrant that the platform will be uninterrupted, error-free, or free of harmful components. This disclaimer is subject to the implied warranties that cannot be excluded under the CPA.</p></section>
        <section><h2 className="text-2xl font-bold mb-4">Indemnification</h2><p className="text-muted-foreground">You agree to indemnify and hold harmless NextSlot, its directors, employees, and agents from any claims, damages, or expenses arising from your use of the platform, your breach of these terms, or your violation of any South African law.</p></section>
        <section><h2 className="text-2xl font-bold mb-4">Termination & Cancellation</h2><p className="text-muted-foreground mb-4">We may suspend or terminate your access to the platform at any time for breach of these terms, with reasonable notice where practicable. Provisions that by their nature should survive termination shall remain in effect.</p><p className="text-muted-foreground mb-4"><strong>Voluntary Cancellation:</strong> You may cancel your NextSlot subscription at any time through your account settings or by contacting our support team. Upon cancellation:</p><ul className="list-disc pl-6 space-y-2 text-muted-foreground mb-4"><li>You will retain full access to the platform and all its features for <strong>30 (thirty) calendar days</strong> from the date of cancellation.</li><li>During this 30-day period, your booking page will remain active and clients can continue to make bookings.</li><li>After the 30-day period, your account will be deactivated and your booking page will no longer be accessible to clients.</li><li>You may download or export your data (including client records and booking history) at any time during the 30-day post-cancellation period.</li><li>No further subscription charges will be applied after cancellation, but no pro-rata refunds will be issued for the current billing period.</li></ul><p className="text-muted-foreground"><strong>Reactivation:</strong> If you wish to reactivate your account after the 30-day period, you may do so by subscribing again. We retain your data for a period of 90 days after account deactivation, after which it may be permanently deleted in accordance with our Privacy Policy and POPIA requirements.</p></section>
        <section><h2 className="text-2xl font-bold mb-4">Amendments</h2><p className="text-muted-foreground">We may amend these Terms of Service from time to time. Material changes will be communicated via the platform or email. Continued use of the platform after such changes constitutes acceptance of the amended terms.</p></section>
        <section><h2 className="text-2xl font-bold mb-4">Governing Law and Jurisdiction</h2><p className="text-muted-foreground">These terms are governed by the laws of the Republic of South Africa. Any disputes arising from these terms shall be subject to the exclusive jurisdiction of the South African courts. Where applicable, disputes may be referred to alternative dispute resolution in accordance with the CPA.</p></section>
        <section><h2 className="text-2xl font-bold mb-4">Severability</h2><p className="text-muted-foreground">If any provision of these terms is found to be invalid or unenforceable under South African law, the remaining provisions shall continue in full force and effect.</p></section>
        <section><h2 className="text-2xl font-bold mb-4">Contact Information</h2><p className="text-muted-foreground">If you have any questions about these Terms of Service, please contact us at:</p><p className="text-muted-foreground mt-4">Email: legal@nextslot.co.za<br />Address: South Africa</p></section>
      </div>
    </main>
  </div>
);

export default SiteTerms;
