// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kjibbbuceipnialfgflt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtqaWJiYnVjZWlwbmlhbGZnZmx0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI3MDQ0NDgsImV4cCI6MjA4ODI4MDQ0OH0.clTpq3pUc-DQaaQgdqdyX-O2xBhJAJAWJFNHlXoxDRE";

/**
 * Safe storage accessor — falls back to an in-memory store when
 * localStorage is unavailable (incognito, privacy browsers, iOS Safari
 * with "Prevent Cross-Site Tracking" enabled, etc.).
 * This ensures the Supabase client always initialises and anonymous
 * RPC calls (like get_month_availability) always fire.
 */
function safeStorage(): Storage {
  try {
    // Quick read/write test — throws SecurityError in strict incognito
    localStorage.setItem('__sb_test__', '1');
    localStorage.removeItem('__sb_test__');
    return localStorage;
  } catch {
    // In-memory fallback — session won't persist across tabs but
    // anon queries work perfectly, which is all the booking page needs.
    const store: Record<string, string> = {};
    return {
      getItem: (k) => store[k] ?? null,
      setItem: (k, v) => { store[k] = v; },
      removeItem: (k) => { delete store[k]; },
      clear: () => { Object.keys(store).forEach((k) => delete store[k]); },
      key: (i) => Object.keys(store)[i] ?? null,
      get length() { return Object.keys(store).length; },
    } as Storage;
  }
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: safeStorage(),
    persistSession: true,
    autoRefreshToken: true,
  }
});
